<?php

namespace App\Models;

use App\Helpers\ClaimReporting;
use Carbon\Carbon;
use Carbon\CarbonPeriod;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class ConversionFlatPercent extends Model implements TimedConversion
{
    use SoftDeletes, ConversionHasSummablePayments, HasTimeSensitivePayments;

    protected $table = 'conversionFlatPercent';

    protected $fillable = [
        'name',
        'program_id',
        'bonus_percent',
        'max_amount',
        'anticipated_payment_date',
        'spend_time_range',
        'clock_start',
        'created_by',
        'updated_by'
    ];

    public function program(): BelongsTo
    {
        return $this->belongsTo(Programs::class, 'program_id');
    }

    public function payment(): MorphMany
    {
        return $this->morphMany(ConversionPayment::class,'conversion');
    }

	public function qualified(): bool {
		$period = $this->getValidPaymentPeriod();

		return $this->paymentSum($period) >= $this->amount;
	}

	public function qualifiedAt(): ?Carbon {
		$i = 0;
		$qualified_at = NULL;
		$relevant_period = $this->getValidPaymentPeriod();

		if($relevant_period == NULL) {
			$payments = $this->payment()
				->orderBy('payment_date')
				->get();
		} else if($relevant_period->isEndExcluded()) {
			$payments = $this->payment()
				->where('payment_date', '>', $relevant_period->getStartDate()->format('Y-m-d'))
				->get();
		} else {
			$payments = $this->payment()
				->whereBetween('payment_date', [
					$relevant_period->getStartDate()->format('Y-m-d'),
					$relevant_period->getEndDate()->format('Y-m-d')
				])->get();
		}

		foreach($payments as $payment) {
			$i += $payment->amount;

			if($i >= $this->amount) {
				$qualified_at = new Carbon($payment->payment_date);
				break;
			}
		}

		return $qualified_at;
	}

    public function save(array $options = [])
    {
        $results = parent::save($options); // TODO: Change the autogenerated stub
        $this->refresh();

        //TODO: put in transaction
        try {
            //Out-dated due to too much change to be done on a save, please use the graphql calculateClaimAllocation mutation to newly created
//            $program = $this->program()->first();
//            $claims = Claims::where('program_id',$program->id)
//                ->whereNotIn('status',['ready to close', 'close'])
//                ->has('rebateReports')
//                ->get()
//            ;
//
//            foreach ( $claims as $claim ){
//                $rebates = $claim->rebateReports()->get();
//
//                if( !empty($rebates) ){
//                    foreach ( $rebates as $rebate ){
//
//                        $claim_rebate = $rebate->pivot;
//                        ClaimReporting::calculateAndSetClaimTotal($claim_rebate);
//                    }
//                }
//            }
        } catch (\Exception $ex){
            throw $ex;
        }

        return $results;
    }
}
