export const associationData = [
  {
    ProductID: 38449,
    Price: 10,
    BenefitID: 51,
    AmountOfPeople: "Member",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38449,
    Price: 20,
    BenefitID: 41,
    AmountOfPeople: "Member plus Spouse",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38449,
    Price: 20,
    BenefitID: 677,
    AmountOfPeople: "Member plus Children",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38449,
    Price: 33,
    BenefitID: 21,
    AmountOfPeople: "Family",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38450,
    Price: 14,
    BenefitID: 51,
    AmountOfPeople: "Member",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38450,
    Price: 28,
    BenefitID: 41,
    AmountOfPeople: "Member plus Spouse",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38450,
    Price: 28,
    BenefitID: 677,
    AmountOfPeople: "Member plus Children",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38450,
    Price: 39,
    BenefitID: 21,
    AmountOfPeople: "Family",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38923,
    Price: 10,
    BenefitID: 51,
    AmountOfPeople: "Member",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38923,
    Price: 20,
    BenefitID: 450,
    AmountOfPeople: "Member + 1",
    State: "Default",
    Label: "National Wellness & Fitness Association",
  },
  {
    ProductID: 38923,
    Price: 28,
    BenefitID: 21,
    AmountOfPeople: "Family",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38928,
    Price: 18,
    BenefitID: 51,
    AmountOfPeople: "Member",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38928,
    Price: 38,
    BenefitID: 41,
    AmountOfPeople: "Member plus Spouse",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38928,
    Price: 46,
    BenefitID: 677,
    AmountOfPeople: "Member plus Children",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38928,
    Price: 59,
    BenefitID: 21,
    AmountOfPeople: "Family",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38941,
    Price: 22,
    BenefitID: 51,
    AmountOfPeople: "Member",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38941,
    Price: 46,
    BenefitID: 41,
    AmountOfPeople: "Member plus Spouse",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38941,
    Price: 54,
    BenefitID: 677,
    AmountOfPeople: "Member plus Children",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
  {
    ProductID: 38941,
    Price: 65,
    BenefitID: 21,
    AmountOfPeople: "Family",
    Label: "National Wellness & Fitness Association",
    State: "Default",
  },
];
