[build]
command = "npm run build"
publish = ".next"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../../"

[dev]
command = "npm run dev"
targetPort = 4200

[[plugins]]
package = "@netlify/plugin-nextjs"
